import numpy as np
import pytest

from vol_surrogate.surrogate.calibrate import SurrogateCalibrator, direct_calibrate
from vol_surrogate.analysis.params_ts import synthetic_param_path, track_parameters
from vol_surrogate.surrogate.lhs import PARAM_BOUNDS
from vol_surrogate.pricing.heston import PARAM_NAMES, iv_grid


@pytest.fixture(scope="module")
def calibrator(checkpoint):
    model, normalizer, meta = checkpoint
    return SurrogateCalibrator(model, normalizer, meta["moneyness"], meta["maturities"])


class TestSurrogateCalibration:
    def test_recovers_params_from_surrogate_quotes(self, calibrator, true_params):
        """Quotes generated BY the surrogate must be recovered near-exactly:
        this isolates the optimiser plumbing from surrogate approximation error."""
        market = calibrator.predict(true_params.as_array())
        res = calibrator.calibrate(market, jac="torch")
        err = np.abs(res.params.as_array() - true_params.as_array())
        # v0, rho, theta are well identified; kappa/xi trade off against each other
        tol = np.array([0.30, 0.005, 0.05, 0.02, 0.002])
        assert np.all(err < tol), f"param errors {dict(zip(PARAM_NAMES, err))}"
        assert res.rmse_iv < 5e-5

    def test_recovers_params_from_fft_quotes(self, calibrator, true_params):
        """Against *analytic* quotes the tolerance includes surrogate model error."""
        market = iv_grid(true_params, calibrator.moneyness, calibrator.maturities)
        res = calibrator.calibrate(market, jac="torch")
        err = np.abs(res.params.as_array() - true_params.as_array())
        tol = np.array([0.75, 0.01, 0.12, 0.05, 0.005])
        assert np.all(err < tol), f"param errors {dict(zip(PARAM_NAMES, err))}"
        assert res.rmse_iv < 3e-3

    def test_fd_and_torch_jacobians_agree(self, calibrator, true_params):
        market = calibrator.predict(true_params.as_array())
        res_t = calibrator.calibrate(market, jac="torch")
        res_f = calibrator.calibrate(market, jac="fd")
        assert np.allclose(res_t.params.as_array(), res_f.params.as_array(), atol=0.05)

    def test_surrogate_calibration_is_fast(self, calibrator, true_params):
        market = calibrator.predict(true_params.as_array())
        res = calibrator.calibrate(market)
        assert res.wall_time_s < 2.0  # typically tens of ms


class TestDirectCalibration:
    def test_direct_recovery_well_identified_params(self, true_params, grid):
        market = iv_grid(true_params, grid["moneyness"], grid["maturities"])
        res = direct_calibrate(market, grid["moneyness"], grid["maturities"], max_nfev=60)
        err = np.abs(res.params.as_array() - true_params.as_array())
        tol = np.array([0.50, 0.01, 0.10, 0.03, 0.003])
        assert np.all(err < tol), f"param errors {dict(zip(PARAM_NAMES, err))}"


class TestTracking:
    def test_synthetic_path_inside_box(self):
        path = synthetic_param_path(n_days=60, seed=42)
        for name in PARAM_NAMES:
            lo, hi = PARAM_BOUNDS[name]
            assert path[name].between(lo, hi).all()
        assert bool((2 * path["kappa"] * path["theta"] >= path["xi"] ** 2).all())

    def test_tracking_follows_regime_shift(self, calibrator):
        path = synthetic_param_path(n_days=12, seed=42).iloc[::2].reset_index(drop=True)
        track = track_parameters(calibrator, param_path=path, noise_bp=10.0)
        assert len(track) == len(path)
        # fitted xi follows true xi closely on surrogate-generated surfaces
        assert np.abs(track["fit_xi"] - track["true_xi"]).mean() < 0.1
